'use client';
import dynamic from 'next/dynamic';
import { motion } from 'framer-motion';
import { ArrowDownRight, ArrowUpRight, Github, Linkedin, Mail, MapPin, Code2, Database, Cloud, Sparkles } from 'lucide-react';

const HeroScene = dynamic(() => import('@/components/hero-scene'), { ssr: false });

type SkillGroup = readonly [string, readonly string[]];
const skills: readonly SkillGroup[] = [
  ['LANGUAGES', ['C#', 'Java', 'Python', 'JavaScript', 'TypeScript']],
  ['BACKEND', ['.NET / ASP.NET Core', 'Web API', 'Azure Functions', 'EF Core', 'LINQ', 'Dapper', 'REST / OData']],
  ['FRONTEND', ['React.js', 'MobX', 'Context API', 'Hooks', 'Microfrontends']],
  ['CLOUD & DATA', ['Azure', 'Blob Storage', 'Key Vault', 'App Configuration', 'PostgreSQL', 'MySQL']],
  ['ENGINEERING', ['OAuth 2.0 / OIDC', 'Okta', 'RBAC', 'SFTP', 'OpenTelemetry', 'Serilog', 'Pandas / ETL']],
];

const projects = [
  { n: '01', title: 'Healthcare Platform', desc: 'Built features for a multi-tenant healthcare/dental application used by doctors and staff, spanning appointments, scheduling, auditability and outside-doctor workflows.', tags: ['C#', '.NET', 'React', 'EF Core', 'MySQL'], accent: '01' },
  { n: '02', title: 'Python ETL Pipeline', desc: 'Designed an automated ETL flow that downloads CSV source data, transforms it with Pandas and loads normalized datasets into PostgreSQL.', tags: ['Python', 'Pandas', 'Azure Functions', 'PostgreSQL'], accent: '02' },
  { n: '03', title: 'QRShare', desc: 'Privacy-first peer-to-peer file sharing using QR bootstrapping, WebRTC and a lightweight signaling layer — no permanent file storage required.', tags: ['React', 'Node.js', 'WebRTC', 'TypeScript'], accent: '03' },
];

function Section({ children, id }: { children: React.ReactNode; id: string }) {
  return <section id={id} className="mx-auto w-full max-w-6xl px-5 py-24 md:px-8">{children}</section>;
}

export default function Home() {
  return <main className="noise grid-bg min-h-screen bg-[#050507] text-white">
    <header className="fixed top-0 z-50 w-full px-4 pt-4"><nav className="glass mx-auto flex max-w-6xl items-center justify-between rounded-full px-5 py-3"><a href="#top" className="text-sm font-bold tracking-[.22em]">HK<span className="text-white/35">/</span>24</a><div className="hidden gap-7 text-xs text-white/55 md:flex"><a href="#work" className="hover:text-white">WORK</a><a href="#stack" className="hover:text-white">STACK</a><a href="#about" className="hover:text-white">ABOUT</a><a href="#contact" className="hover:text-white">CONTACT</a></div><a href="mailto:harshkumar07@gmail.com" className="rounded-full bg-white px-4 py-2 text-xs font-semibold text-black">LET'S TALK</a></nav></header>
    <section id="top" className="relative flex min-h-[92vh] items-center overflow-hidden"><div className="absolute left-[8%] top-[18%] h-64 w-64 rounded-full bg-white/10 orb"/><HeroScene/><div className="mx-auto w-full max-w-6xl px-5 pt-20 md:px-8"><div className="max-w-4xl"><motion.p initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="mb-6 flex items-center gap-3 text-xs tracking-[.28em] text-white/45"><span className="h-px w-10 bg-white/30"/> SOFTWARE ENGINEER · BENGALURU</motion.p><motion.h1 initial={{ opacity: 0, y: 25 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .1 }} className="text-[clamp(3.5rem,10vw,9rem)] font-semibold leading-[.84] tracking-[-.07em]">BUILDING<br/><span className="gradient-text">DIGITAL SYSTEMS.</span></motion.h1><motion.p initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: .25 }} className="mt-9 max-w-2xl text-base leading-7 text-white/55 md:text-lg">I’m Harsh — a full stack developer focused on <span className="text-white">C# / .NET, React, Python and Azure</span>. I turn complex product requirements into fast, reliable experiences.</motion.p><div className="mt-9 flex flex-wrap gap-3"><a href="#work" className="group rounded-full bg-white px-6 py-3 text-sm font-semibold text-black">Explore my work <ArrowDownRight className="ml-2 inline size-4 transition-transform group-hover:translate-y-1 group-hover:rotate-12"/></a><a href="https://github.com/harshkumar07" target="_blank" rel="noreferrer" className="glass rounded-full px-6 py-3 text-sm text-white/80">GitHub <ArrowUpRight className="ml-2 inline size-4"/></a></div></div></div></section>
    <div className="border-y border-white/[.07] bg-white/[.015]"><div className="mx-auto grid max-w-6xl grid-cols-2 px-5 md:grid-cols-4 md:px-8">{[['~2', 'YEARS BUILDING'], ['C#', 'CORE LANGUAGE'], ['AZURE', 'CLOUD'], ['FULL', 'STACK MINDSET']].map(([a, b]) => <div key={b} className="border-r border-white/[.07] px-5 py-7 last:border-0"><div className="text-2xl font-semibold tracking-tight">{a}</div><div className="mt-1 text-[10px] tracking-[.2em] text-white/35">{b}</div></div>)}</div></div>
    <Section id="work"><div className="mb-12 flex items-end justify-between"><div><p className="mb-3 text-xs tracking-[.25em] text-white/35">SELECTED WORK</p><h2 className="text-4xl font-semibold tracking-tight md:text-6xl">Things I build.</h2></div><ArrowDownRight className="hidden size-9 text-white/25 md:block"/></div><div className="space-y-4">{projects.map((p) => <motion.article key={p.n} whileHover={{ y: -5 }} className="glass group relative overflow-hidden rounded-3xl p-6 md:p-9"><div className="absolute right-7 top-5 text-7xl font-bold tracking-[-.08em] text-white/[.035]">{p.accent}</div><div className="grid gap-8 md:grid-cols-[100px_1fr_260px] md:items-center"><span className="text-xs text-white/30">/{p.n}</span><div><h3 className="text-2xl font-medium md:text-3xl">{p.title}</h3><p className="mt-3 max-w-2xl text-sm leading-6 text-white/45">{p.desc}</p><div className="mt-5 flex flex-wrap gap-2">{p.tags.map((t) => <span key={t} className="rounded-full border border-white/10 px-3 py-1 text-[10px] text-white/55">{t}</span>)}</div></div><div className="hidden justify-end md:flex"><span className="flex size-12 items-center justify-center rounded-full border border-white/10 transition-all group-hover:bg-white group-hover:text-black"><ArrowUpRight className="size-5"/></span></div></div></motion.article>)}</div></Section>
    <Section id="stack"><div className="mb-12"><p className="mb-3 text-xs tracking-[.25em] text-white/35">THE TOOLKIT</p><h2 className="text-4xl font-semibold tracking-tight md:text-6xl">My stack, in layers.</h2></div><div className="grid gap-3 md:grid-cols-2">{skills.map(([name, items], i) => <motion.div key={name} initial={{ opacity: 0, y: 15 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: i * .05 }} className="glass rounded-3xl p-6"><div className="mb-5 flex items-center justify-between"><span className="text-xs tracking-[.2em] text-white/35">0{i + 1}</span><span className="text-xs text-white/55">{name}</span></div><div className="flex flex-wrap gap-2">{items.map((x) => <span key={x} className="rounded-lg bg-white/[.045] px-3 py-2 text-xs text-white/75">{x}</span>)}</div></motion.div>)}</div></Section>
    <Section id="about"><div className="grid gap-12 md:grid-cols-[1fr_1.4fr] md:items-center"><div><p className="mb-3 text-xs tracking-[.25em] text-white/35">A LITTLE ABOUT ME</p><h2 className="text-4xl font-semibold tracking-tight md:text-6xl">Engineering with<br/><span className="text-white/35">product sense.</span></h2></div><div className="space-y-5 text-base leading-8 text-white/55"><p>I work on production software where backend architecture, APIs, data and polished interfaces have to fit together. My day-to-day toolkit is C#/.NET and React, with Python for data workflows and Azure for cloud infrastructure.</p><p>I care about performance, clean boundaries and systems that are easy to reason about — from query optimization and caching to authentication, observability and multi-tenant configuration.</p><div className="grid grid-cols-2 gap-3 pt-3">{[[Code2, 'Application engineering'], [Database, 'Data & performance'], [Cloud, 'Cloud systems'], [Sparkles, 'AI & automation']].map(([Icon, t]) => { const I = Icon as typeof Code2; return <div key={t as string} className="glass rounded-2xl p-4"><I className="mb-3 size-4 text-white/60"/><span className="text-xs text-white/55">{t as string}</span></div>; })}</div></div></div></Section>
    <section id="contact" className="relative overflow-hidden border-t border-white/[.07]"><div className="mx-auto max-w-6xl px-5 py-28 md:px-8"><p className="text-xs tracking-[.25em] text-white/35">HAVE A PROJECT / OPPORTUNITY?</p><h2 className="mt-5 max-w-4xl text-[clamp(3rem,8vw,7rem)] font-semibold leading-[.9] tracking-[-.06em]">LET'S MAKE<br/><span className="gradient-text">SOMETHING GREAT.</span></h2><div className="mt-10 flex flex-wrap gap-3"><a href="mailto:harshkumar07@gmail.com" className="rounded-full bg-white px-6 py-3 text-sm font-semibold text-black"><Mail className="mr-2 inline size-4"/> Email me</a><a href="https://www.linkedin.com/in/harshkumargupta/" target="_blank" rel="noreferrer" className="glass rounded-full px-6 py-3 text-sm">LinkedIn <ArrowUpRight className="ml-2 inline size-4"/></a><a href="https://github.com/harshkumar07" target="_blank" rel="noreferrer" className="glass rounded-full px-6 py-3 text-sm"><Github className="mr-2 inline size-4"/> GitHub</a></div><div className="mt-20 flex items-center gap-2 text-xs text-white/25"><MapPin className="size-3"/> Bengaluru, India <span className="mx-2">·</span> Available for great problems</div></div></section>
    <footer className="border-t border-white/[.07] px-5 py-7 text-center text-[10px] tracking-[.2em] text-white/25">HARSH KUMAR · FULL STACK DEVELOPER · 2026</footer>
  </main>;
}
