'use client';
import dynamic from 'next/dynamic';
import { motion } from 'framer-motion';
import { ArrowDownRight, ArrowUpRight, Mail, MapPin, Code2, Database, Cloud, Sparkles, Download, FileText, ShieldCheck, Workflow, BrainCircuit } from 'lucide-react';

const HeroScene = dynamic(() => import('@/components/hero-scene'), { ssr: false });

type SkillGroup = readonly [string, readonly string[]];
const skills: readonly SkillGroup[] = [
  ['LANGUAGES', ['C#', 'Java', 'Python', 'JavaScript', 'TypeScript']],
  ['BACKEND', ['.NET / ASP.NET Core', 'Web API', 'Azure Functions', 'EF Core', 'LINQ', 'Dapper', 'REST / OData']],
  ['FRONTEND', ['React.js', 'MobX', 'Context API', 'Hooks', 'Microfrontends']],
  ['CLOUD & DATA', ['Azure', 'Blob Storage', 'Key Vault', 'App Configuration', 'PostgreSQL', 'MySQL']],
  ['ENGINEERING', ['OAuth 2.0 / OIDC', 'Okta', 'RBAC', 'SFTP', 'OpenTelemetry', 'Serilog', 'Pandas / ETL']],
];

const projects = [
  { n: '01', title: 'Healthcare Platform', desc: 'Production healthcare/dental software used by doctors and staff. Built scheduling, appointments, auditability, outside-doctor workflows and multi-tenant configuration across backend and frontend.', tags: ['C#', '.NET', 'React', 'EF Core', 'MySQL'], accent: '01' },
  { n: '02', title: 'Python ETL Pipeline', desc: 'Automated SFTP → Azure Blob → Python ETL flow. CSV data is downloaded, validated and transformed with Pandas before being loaded into PostgreSQL for downstream use.', tags: ['Python', 'Pandas', 'Azure Functions', 'Blob', 'PostgreSQL'], accent: '02' },
  { n: '03', title: 'QRShare', desc: 'Privacy-first peer-to-peer file sharing using QR bootstrapping, WebRTC and lightweight signaling — designed without permanent file storage.', tags: ['React', 'Node.js', 'WebRTC', 'TypeScript'], accent: '03' },
  { n: '04', title: 'PayMe App', desc: 'MERN-based payment application with JWT authentication, transaction management, responsive UI and real-time updates.', tags: ['MongoDB', 'Express', 'React', 'Node.js', 'JWT'], accent: '04' },
];

const experience = [
  ['AUG 2024 — PRESENT', 'Software Engineer · HealthAsyst', 'Building production healthcare software with C#/.NET, React, Azure and Python.'],
  ['PRODUCTION IMPACT', '10,000+ appointments / month', 'Worked on Month View scheduling, doctor/chair/location filtering, working hours, holidays and dynamic availability.'],
  ['CLOUD & DATA', 'Azure + PostgreSQL + Python', 'Worked with Azure Functions, Blob Storage, Key Vault, App Configuration, SFTP ingestion and Entra Managed Identity.'],
];

function Section({ children, id }: { children: React.ReactNode; id: string }) {
  return <section id={id} className="mx-auto w-full max-w-6xl px-5 py-24 md:px-8">{children}</section>;
}

const fadeUp = { initial: { opacity: 0, y: 24 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, amount: 0.18 }, transition: { duration: 0.65 } };

export default function Home() {
  return <main className="noise grid-bg min-h-screen bg-[#050507] text-white">
    <header className="fixed top-0 z-50 w-full px-4 pt-4"><nav className="glass nav-glow mx-auto flex max-w-6xl items-center justify-between rounded-full px-5 py-3"><a href="#top" className="text-sm font-bold tracking-[.22em]">HK<span className="text-cyan-300/70">/</span>24</a><div className="hidden gap-7 text-xs text-white/55 md:flex"><a href="#work" className="nav-link">WORK</a><a href="#experience" className="nav-link">EXPERIENCE</a><a href="#stack" className="nav-link">STACK</a><a href="#about" className="nav-link">ABOUT</a><a href="#contact" className="nav-link">CONTACT</a></div><a href="mailto:Harshku068@gmail.com" className="magnetic rounded-full bg-white px-4 py-2 text-xs font-semibold text-black">LET'S TALK</a></nav></header>

    <section id="top" className="relative flex min-h-[94vh] items-center overflow-hidden"><div className="hero-aura absolute left-[8%] top-[18%] h-72 w-72 rounded-full bg-cyan-400/20"/><div className="hero-aura hero-aura-two absolute right-[8%] bottom-[8%] h-80 w-80 rounded-full bg-violet-500/20"/><HeroScene/><div className="pointer-events-none absolute inset-x-0 bottom-0 h-40 bg-gradient-to-t from-[#050507] to-transparent"/><div className="mx-auto w-full max-w-6xl px-5 pt-20 md:px-8"><div className="max-w-5xl"><motion.p initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="mb-6 flex items-center gap-3 text-xs tracking-[.28em] text-cyan-100/55"><span className="h-px w-10 bg-cyan-300/50"/> SOFTWARE ENGINEER · BENGALURU</motion.p><motion.h1 initial={{ opacity: 0, y: 25 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .1, duration: .8 }} className="text-[clamp(3.5rem,10vw,9rem)] font-semibold leading-[.84] tracking-[-.07em]">BUILDING<br/><span className="gradient-text">DIGITAL SYSTEMS.</span></motion.h1><motion.p initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: .25 }} className="mt-9 max-w-2xl text-base leading-7 text-white/55 md:text-lg">I’m Harsh — a full stack developer focused on <span className="text-cyan-100">C# / .NET, React, Python and Azure</span>. I build reliable production systems, data workflows and polished product experiences.</motion.p><motion.div initial={{ opacity: 0, y: 15 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .35 }} className="mt-9 flex flex-wrap gap-3"><a href="#work" className="magnetic group rounded-full bg-white px-6 py-3 text-sm font-semibold text-black">Explore my work <ArrowDownRight className="ml-2 inline size-4 transition-transform group-hover:translate-y-1 group-hover:rotate-12"/></a><a href="/resume.pdf" target="_blank" rel="noreferrer" className="glass magnetic rounded-full px-5 py-3 text-sm text-white/85"><FileText className="mr-2 inline size-4"/> View Resume</a><a href="/resume.pdf" download="Harsh-Kumar-Resume.pdf" className="glass magnetic rounded-full px-5 py-3 text-sm text-white/85"><Download className="mr-2 inline size-4"/> Download Resume</a></motion.div></div></div></section>

    <div className="border-y border-white/[.07] bg-white/[.015]"><div className="mx-auto grid max-w-6xl grid-cols-2 px-5 md:grid-cols-4 md:px-8">{[['~2', 'YEARS BUILDING'], ['C#', 'CORE LANGUAGE'], ['AZURE', 'CLOUD'], ['10K+', 'APPOINTMENTS / MONTH']].map(([a, b]) => <div key={b} className="stat-cell border-r border-white/[.07] px-5 py-7 last:border-0"><div className="text-2xl font-semibold tracking-tight">{a}</div><div className="mt-1 text-[10px] tracking-[.2em] text-white/35">{b}</div></div>)}</div></div>

    <Section id="experience"><motion.div {...fadeUp} className="mb-12"><p className="mb-3 text-xs tracking-[.25em] text-cyan-200/45">EXPERIENCE</p><h2 className="text-4xl font-semibold tracking-tight md:text-6xl">Where I build.</h2></motion.div><div className="relative ml-2 border-l border-cyan-300/15 pl-7 md:ml-5 md:pl-10">{experience.map(([date, title, desc], i) => <motion.div key={title} {...fadeUp} transition={{ delay: i * .08, duration: .65 }} className="timeline-item relative mb-5 last:mb-0"><span className="timeline-dot absolute -left-[35px] top-6 size-2 rounded-full bg-cyan-300 shadow-[0_0_18px_rgba(103,232,249,.9)] md:-left-[45px]"/><div className="glass hover-lift rounded-3xl p-6 md:p-8"><div className="text-[10px] tracking-[.22em] text-cyan-200/45">{date}</div><h3 className="mt-2 text-xl font-medium md:text-2xl">{title}</h3><p className="mt-3 max-w-3xl text-sm leading-6 text-white/45">{desc}</p></div></motion.div>)}</div></Section>

    <Section id="work"><motion.div {...fadeUp} className="mb-12 flex items-end justify-between"><div><p className="mb-3 text-xs tracking-[.25em] text-cyan-200/45">SELECTED WORK</p><h2 className="text-4xl font-semibold tracking-tight md:text-6xl">Things I build.</h2></div><ArrowDownRight className="hidden size-9 text-cyan-200/25 md:block"/></motion.div><div className="grid gap-4 md:grid-cols-2">{projects.map((p, i) => <motion.article key={p.n} initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .15 }} transition={{ delay: i * .07 }} whileHover={{ y: -8 }} className="project-card glass group relative overflow-hidden rounded-3xl p-6 md:p-8"><div className="project-glow"/><div className="absolute right-7 top-4 text-7xl font-bold tracking-[-.08em] text-white/[.035]">{p.accent}</div><div className="relative"><div className="mb-8 flex items-center justify-between"><span className="rounded-full border border-cyan-200/10 px-3 py-1 text-[10px] tracking-[.2em] text-cyan-100/45">/{p.n}</span><ArrowUpRight className="size-5 text-white/25 transition-all group-hover:-translate-y-1 group-hover:translate-x-1 group-hover:text-cyan-200"/></div><h3 className="text-2xl font-medium md:text-3xl">{p.title}</h3><p className="mt-3 max-w-xl text-sm leading-6 text-white/45">{p.desc}</p><div className="mt-6 flex flex-wrap gap-2">{p.tags.map((t) => <span key={t} className="rounded-full border border-white/10 bg-white/[.025] px-3 py-1 text-[10px] text-white/55 transition-colors group-hover:border-cyan-200/15">{t}</span>)}</div></div></motion.article>)}</div></Section>

    <Section id="stack"><motion.div {...fadeUp} className="mb-12"><p className="mb-3 text-xs tracking-[.25em] text-cyan-200/45">THE TOOLKIT</p><h2 className="text-4xl font-semibold tracking-tight md:text-6xl">My stack, in layers.</h2></motion.div><div className="grid gap-3 md:grid-cols-2">{skills.map(([name, items], i) => <motion.div key={name} initial={{ opacity: 0, y: 15 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: i * .05 }} className="glass hover-lift rounded-3xl p-6"><div className="mb-5 flex items-center justify-between"><span className="text-xs tracking-[.2em] text-cyan-200/35">0{i + 1}</span><span className="text-xs text-white/55">{name}</span></div><div className="flex flex-wrap gap-2">{items.map((x) => <span key={x} className="skill-pill rounded-lg bg-white/[.045] px-3 py-2 text-xs text-white/75">{x}</span>)}</div></motion.div>)}</div></Section>

    <Section id="about"><div className="grid gap-12 md:grid-cols-[1fr_1.4fr] md:items-center"><motion.div {...fadeUp}><p className="mb-3 text-xs tracking-[.25em] text-cyan-200/45">A LITTLE ABOUT ME</p><h2 className="text-4xl font-semibold tracking-tight md:text-6xl">Engineering with<br/><span className="text-white/35">product sense.</span></h2></motion.div><motion.div {...fadeUp} className="space-y-5 text-base leading-8 text-white/55"><p>I work on production software where backend architecture, APIs, data and polished interfaces have to fit together. My day-to-day toolkit is C#/.NET and React, with Python for data workflows and Azure for cloud systems.</p><p>I care about performance, clean boundaries and systems that are easy to reason about — from query optimization and caching to authentication, observability and multi-tenant configuration.</p><div className="grid grid-cols-2 gap-3 pt-3">{[[Code2, 'Application engineering'], [Database, 'Data & performance'], [Cloud, 'Cloud systems'], [Sparkles, 'AI & automation']].map(([Icon, t]) => { const I = Icon as typeof Code2; return <div key={t as string} className="glass hover-lift rounded-2xl p-4"><I className="mb-3 size-4 text-cyan-200/65"/><span className="text-xs text-white/55">{t as string}</span></div>; })}</div></motion.div></div></Section>

    <Section id="capabilities"><motion.div {...fadeUp} className="mb-10"><p className="mb-3 text-xs tracking-[.25em] text-cyan-200/45">WHAT I BRING</p><h2 className="text-4xl font-semibold tracking-tight md:text-6xl">Beyond the stack.</h2></motion.div><div className="grid gap-3 md:grid-cols-3">{[[ShieldCheck, 'Secure by design', 'Okta OIDC/OAuth 2.0, token-based authorization and RBAC across protected APIs and resources.'], [Workflow, 'Data in motion', 'SFTP ingestion, Blob Storage, Python Functions, Pandas transformations and PostgreSQL loading.'], [BrainCircuit, 'AI & automation', 'Azure AI Foundry and LLM-powered analysis for structured summaries and recommendations.']].map(([Icon, title, desc], i) => { const I = Icon as typeof ShieldCheck; return <motion.div key={title as string} {...fadeUp} transition={{ delay: i * .08, duration: .65 }} className="glass hover-lift rounded-3xl p-6 md:p-7"><I className="size-5 text-cyan-200/70"/><h3 className="mt-6 text-lg font-medium">{title as string}</h3><p className="mt-3 text-sm leading-6 text-white/45">{desc as string}</p></motion.div>; })}</div></Section>

    <section id="contact" className="relative overflow-hidden border-t border-white/[.07]"><div className="contact-aura absolute left-1/2 top-1/2 size-[28rem] -translate-x-1/2 -translate-y-1/2 rounded-full bg-cyan-400/10"/><div className="relative mx-auto max-w-6xl px-5 py-28 md:px-8"><p className="text-xs tracking-[.25em] text-cyan-200/45">HAVE A PROJECT / OPPORTUNITY?</p><h2 className="mt-5 max-w-4xl text-[clamp(3rem,8vw,7rem)] font-semibold leading-[.9] tracking-[-.06em]">LET'S MAKE<br/><span className="gradient-text">SOMETHING GREAT.</span></h2><div className="mt-10 flex flex-wrap gap-3"><a href="mailto:Harshku068@gmail.com" className="magnetic rounded-full bg-white px-6 py-3 text-sm font-semibold text-black"><Mail className="mr-2 inline size-4"/> Email me</a><a href="/resume.pdf" target="_blank" rel="noreferrer" className="magnetic glass rounded-full px-6 py-3 text-sm"><FileText className="mr-2 inline size-4"/> View Resume</a><a href="/resume.pdf" download="Harsh-Kumar-Resume.pdf" className="magnetic glass rounded-full px-6 py-3 text-sm"><Download className="mr-2 inline size-4"/> Download Resume</a><a href="https://www.linkedin.com/in/harshkumargupta/" target="_blank" rel="noreferrer" className="magnetic glass rounded-full px-6 py-3 text-sm">LinkedIn <ArrowUpRight className="ml-2 inline size-4"/></a><a href="https://github.com/harshkumar07" target="_blank" rel="noreferrer" className="magnetic glass rounded-full px-6 py-3 text-sm">GitHub <ArrowUpRight className="ml-2 inline size-4"/></a></div><div className="mt-20 flex items-center gap-2 text-xs text-white/25"><MapPin className="size-3"/> Bengaluru, India <span className="mx-2">·</span> Available for great problems</div></div></section>
    <footer className="border-t border-white/[.07] px-5 py-7 text-center text-[10px] tracking-[.2em] text-white/25">HARSH KUMAR · FULL STACK DEVELOPER · 2026</footer>
  </main>;
}
