'use client';

import { useState } from 'react';
import { ArrowLeft, Copy, Check, Terminal, Sparkles } from 'lucide-react';

const commands=['whoami','stack --core','system --focus','contact --email'];
const outputs:{[key:string]:string}={whoami:'harsh@bengaluru:~$ Software Engineer · Full Stack Developer', 'stack --core':'C# · .NET · React · Python · Azure · PostgreSQL · MySQL', 'system --focus':'Production APIs · cloud services · data workflows · product UI', 'contact --email':'Harshku068@gmail.com'};

export default function Lab(){const [cmd,setCmd]=useState('whoami');const [copied,setCopied]=useState(false);const copy=async()=>{await navigator.clipboard?.writeText(outputs[cmd]);setCopied(true);setTimeout(()=>setCopied(false),1200)};return <main className="site-shell min-h-screen text-white"><div className="mx-auto max-w-6xl px-5 py-8 md:px-8"><a href="/" className="inline-flex items-center gap-2 text-xs text-white/45 hover:text-white"><ArrowLeft size={15}/> BACK HOME</a><div className="pt-24"><div className="eyebrow-small"><Terminal size={13}/> DEVELOPER LAB</div><h1 className="mt-4 text-[clamp(3.5rem,9vw,8rem)] font-semibold leading-[.82] tracking-[-.075em]">NO SLIDES.<br/><span className="gradient-text">JUST TERMINAL.</span></h1><p className="mt-8 max-w-2xl text-white/45">A small interactive corner of the portfolio. Click a command — the terminal answers.</p></div><div className="mt-12 overflow-hidden rounded-3xl border border-white/10 bg-[#05070b] shadow-2xl"><div className="flex items-center gap-2 border-b border-white/8 px-5 py-4"><i className="size-2 rounded-full bg-red-400/70"/><i className="size-2 rounded-full bg-yellow-300/70"/><i className="size-2 rounded-full bg-green-400/70"/><span className="ml-3 text-[10px] text-white/25">harsh@portfolio ~ /lab</span></div><div className="grid md:grid-cols-[220px_1fr]"><div className="border-b border-white/8 p-4 md:border-b-0 md:border-r">{commands.map(c=><button key={c} onClick={()=>setCmd(c)} className={`mb-1 block w-full rounded-xl px-4 py-3 text-left font-mono text-xs transition ${cmd===c?'bg-cyan-300/10 text-cyan-200':'text-white/40 hover:bg-white/5 hover:text-white'}`}>$ {c}</button>)}</div><div className="min-h-[300px] p-7 font-mono text-sm"><div className="text-white/25">harsh@portfolio:~$ {cmd}</div><div className="mt-5 text-cyan-200">{outputs[cmd]}</div><button onClick={copy} className="mt-8 inline-flex items-center gap-2 rounded-full border border-white/10 px-4 py-2 text-[11px] text-white/45 hover:text-white">{copied?<Check size={14}/>:<Copy size={14}/>} {copied?'COPIED':'COPY OUTPUT'}</button></div></div></div><div className="mt-8 flex items-center gap-2 text-xs text-white/25"><Sparkles size={13}/> Built for the portfolio — not a fake shell.</div></div></main>}
